### ISSUE TITLE
When I run semantic_role_labeling.py ,I got a error.

### ISSUE THREAD

**Issue by sherlockfeng1995** [cshizhe/hgr_v2t#18]
allennlp.common.checks.ConfigurationError: srl not in acceptable choices for dataset_reader.type

My config code for predictor is 

    **archive=load_archive('bert-base-srl-2019.06.17')
    predictor=Predictor.from_archive(archive,'video-text classifier')**

**Comment by DJCCRK** [comment]
I have this error too. Did you solve this problem?

**Comment by wongtiantian** [comment]
Hi, I got the same error with you. Did you solved this problem, how you deal with it?

**Comment by DJCCRK** [comment]
you can try this way
Meet the same problem and finally found the problem is that I have not successfully installed the package. Please try "pip install allennlp==1.0.0 allennlp-models==1.0.0".



发自我的iPhone


------------------ Original ------------------
From: wongtiantian ***@***.***&gt;
Date: Wed,Sep 15,2021 6:08 PM
To: cshizhe/hgr_v2t ***@***.***&gt;
Cc: DJCCRK ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [cshizhe/hgr_v2t] When I run semantic_role_labeling.py ,I got a error. (#18)





 
Hi, I got the same error with you. Did you solved this problem, how you deal with it?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
