### ISSUE TITLE
If there is no verb in the sentence, what should we do with it？

### ISSUE THREAD

**Issue by lDarryll** [cshizhe/hgr_v2t#25]
If there is no verb in the sentence, what should we do with it

**Comment by cshizhe** [comment]
The model combines cross-modal scores from three levels (the global sentence, verbs,  and noun phrases). So when there is no verb in the sentence, the other two levels would be used for cross-modal matching.

**Comment by lDarryll** [comment]
![image](https://user-images.githubusercontent.com/34019070/126773152-5f9e5241-9088-4144-b254-19448cde20d4.png)
However, if there are no verbs, an error will be prompted when generating the graph. Do I ignore it or eliminate the sentence without verbs, or add verbs manually

**Comment by cshizhe** [comment]
Does your error come from the "assert" in the red rectangle? 
This assert line is to ensure that the number of tokenized words from spacy and that from srl toolkit are the same. Otherwise the word indexes are not aligned and we cannot get correct results.
In this case, you probably should not augment the parsed graph automatically. Manual process should be fine.

**Comment by lDarryll** [comment]
Do you have any other augment methods or tools besides manual augment ? In addition, is it necessary to augment the graph? If not, can I use the non enhanced graph?

**Comment by cshizhe** [comment]
In my case, most of the sentences can be correctly parsed, so I didn't do any manual process and the performance was good.
I think it depends on your data how to augment the graph. You may need other NLP parsing tools if there are too many failure cases.
